services:
  - type: web
    name: suporte-rm-dashboard
    runtime: python
    rootDir: dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GLPI_URL
        sync: false
      - key: GLPI_APP_TOKEN
        sync: false
      - key: GLPI_USER_TOKEN
        sync: false
